typography_spectrum: 0.13966913986951113
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.38924748613499105
  lightness: 0.9716198749374598
  saturation: 0.39138043974526227
  rhythmicContrast: 0.7167472855653614
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9188541506882757
analytics:
  google: null
  facebook: null
  twitter: null
name: aiste
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
